
using System.Reflection;
using UnityEditor;
using UnityEngine;

[CustomEditor(typeof(CardScriptable))]
public class CardScriptableEditor : Editor
{
    private FieldInfo Name;
    private FieldInfo Desc;
    private FieldInfo cardType;
    private FieldInfo damageAmount;
    private FieldInfo cardEffects;

    private CardScriptable current;


    private void OnEnable()
    {

        current = target as CardScriptable;

        Name = GetBackingField(current, "Name");
        Desc = GetBackingField(current, "Description");
        cardType = GetBackingField(current, "type");
        damageAmount = GetBackingField(current, "damageAmount");
        cardEffects = GetBackingField(current, "cardEffects");
    }


    public override void OnInspectorGUI()
    {
        EditorGUI.BeginChangeCheck();
        Name.SetValue(current, EditorGUILayout.TextField("Name", (string)Name.GetValue(current)));
        EditorGUILayout.LabelField("Description");
        Desc.SetValue(current, EditorGUILayout.TextArea((string)Desc.GetValue(current), new GUILayoutOption[]
        {
            GUILayout.Height(25)
        }));

        cardType.SetValue(current, (int)(CardTypeEnum)EditorGUILayout.EnumPopup("Card Type", (CardTypeEnum)cardType.GetValue(current)));
        
        if ((CardTypeEnum)cardType.GetValue(current) != CardTypeEnum.CHARACTER)
        {
            damageAmount.SetValue(current, EditorGUILayout.Slider(1, HpManager.maxHp, (float)damageAmount.GetValue(current)));
            //do card effects here
        }



        if (EditorGUI.EndChangeCheck()) serializedObject.ApplyModifiedProperties();
    }

    //nasty nasty reflection!!
    //but unity is worse than me with its login so 
    //I think we're even!!
    private string GetBackingFieldName(string propertyName)
    {
        //Backing fields are fields generated by c#'s compiler when a field has getters and setters defined.
        //They are usefull for unity as it doesn't support the serialization of properties (fields with getters and setters)
        //Here I'm taking advantage of them to be able to serialize properties with private sets to the editor.
        return string.Format("<{0}>k__BackingField", propertyName);

    }

    private FieldInfo GetBackingField(object obj, string propertyName)
    {
        return obj.GetType().GetField(GetBackingFieldName(propertyName), BindingFlags.Instance | BindingFlags.NonPublic);
    }
}
