using System.Reflection;
using UnityEditor;
using UnityEditor.Rendering;
using UnityEngine.UI;

[CustomEditor(typeof(PronounToggle)), CanEditMultipleObjects]
public class TogglePronounEditor : Editor
{

    FieldInfo representingPronoun;

    public void OnEnable()
    {
        representingPronoun = GetBackingField(target, "representingPronoun");
    }

    public override void OnInspectorGUI()
    {
        base.OnInspectorGUI();

        //if you couldn't tell by how shitty this implementation is, IDGAF about how it looks in the editor

        representingPronoun.SetValue(target, (pronouns)EditorGUILayout.EnumPopup((pronouns)representingPronoun.GetValue(target)));
    }

    private FieldInfo GetBackingField(object obj, string propertyName)
    {
        return obj.GetType().GetField(GetBackingFieldName(propertyName), BindingFlags.Instance | BindingFlags.NonPublic);
    }

    //nasty nasty reflection!!
    //but unity is worse than me with its login so 
    //I think we're even!!
    private string GetBackingFieldName(string propertyName)
    {
        //Backing fields are fields generated by c#'s compiler when a field has getters and setters defined.
        //They are usefull for unity as it doesn't support the serialization of properties (fields with getters and setters)
        //Here I'm taking advantage of them to be able to serialize properties with private sets to the editor.
        return string.Format("<{0}>k__BackingField", propertyName);

    }
}